package com.skuri.skuri_backend.domain.notification.entity;

public enum NotificationType {
    PARTY_CREATED,
    PARTY_JOIN_REQUEST,
    PARTY_JOIN_ACCEPTED,
    PARTY_JOIN_DECLINED,
    PARTY_CLOSED,
    PARTY_REOPENED,
    PARTY_ARRIVED,
    PARTY_ENDED,
    MEMBER_KICKED,
    SETTLEMENT_COMPLETED,
    CHAT_MESSAGE,
    POST_LIKED,
    COMMENT_CREATED,
    NOTICE,
    APP_NOTICE,
    ACADEMIC_SCHEDULE,
    FRIEND_REQUEST,
    FRIEND_ACCEPTED,
    FRIEND_DECLINED,
    PARTY_INVITATION,
    CHAT_ROOM_INVITATION
}
